name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # Core scientific computing packages (major.minor versions only)
  - numpy=2.0
  - scipy=1.13
  - matplotlib=3.9
  - h5py=3.12
  # Critical package with specific version
  - decorator=5.1
  # Jupyter ecosystem
  - jupyter=1.0
  - notebook=7.2
  - jupyterlab=4.2
  - ipykernel=6.29
  - ipywidgets=8.1
  - jupyter_client=8.6
  - jupyter_core=5.7
  - jupyter_server=2.14
  # Data science packages
  - pandas=2.2
  - seaborn=0.13
  # Essential utilities
  - pip=24.2
  - setuptools=72.2
  - wheel=0.44
  - pyyaml=6.0
  - requests=2.32